---
abstract: 'Determine Brazilian public holidays'
author:
  - 'Breno G. de Oliveira <garu@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3601'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Date-Holidays-BR
provides:
  Date::Holidays::BR:
    file: lib/Date/Holidays/BR.pm
    version: 0.01
requires:
  Date::Easter: 0
  Date::Holidays::Super: 0
  Time::JulianDay: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
